### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/petle#1]
obecnie Twoja choinka dla wysokosci 5 ma takie ilosci gwiazdek: `1, 2, 4, 6, 8`, a powinna miec: `1, 3, 5, 7, 9` (kazdy poziom o 2 wiecej niz poprzedni)

**Comment by zdolny** [comment]
- [x] slowo kluczowe `var` jest uzywane za pierwszym razem jak deklarujesz zmienna. Kiedy pozniej zmieniasz jej wartosc, to nie musisz jej na nowo deklarowac, czyli:
```
var a;
a = 1;
a = a + 1;
var b = 5;
b = b - 2;
```
- [x] zapis `star += '*'` (dodaj i przypisz) jest skrotem od `star = star + '*'` - nie musisz tego przypisywac do zmiennej star
- [x] teraz Twoja choinka jest o jeden poziom za niska, po wywolaniu `rysujChoinke(1);` powinna pojawic sie jedna gwiazdka

**Comment by zdolny** [comment]
git!
